#!/bin/bash

# Check for lock file; else create it
LOCK="$HOME/.config/niri/scripts/locker-$WAYLAND_DISPLAY.lock"
if [[ -a $LOCK ]]
then
  echo "Locker error: Lock file already exists!"
  exit 1
fi
touch $LOCK

# Fork a second swayidle to blank screen faster
swayidle timeout 30 'niri msg action power-off-monitors' \
  resume 'niri msg action power-on-monitors' &
CHILD=$!

# Wake up display to get screenshot
niri msg action power-on-monitors

# Get screenshot & blur for background
grimshot save screen - | magick - -blur 0x5 /tmp/locker_${WAYLAND_DISPLAY}_bg
# Start a screen transition
niri msg action do-screen-transition -d 1000
# Start gtklock
gtklock -t '%I:%M:%S %P' \
  --date-format '%F — %A' \
  -b /tmp/locker_${WAYLAND_DISPLAY}_bg \
  -H -T 15 \
  -g 'Breeze'

# Cleanup:
# Kill child
kill $CHILD || kill -9 $CHILD
# Release lock
rm $LOCK || echo -e "Locker error: Could not remove lock file at:\n\t$LOCK"

# Wake up display
niri msg action power-on-monitors
