#!/usr/bin/env sh

BRIGHTNESS=$(brightnessctl get)
BMAX=$(brightnessctl max)
BRIGHTNESS=$(echo "b = e(l(${BRIGHTNESS}/${BMAX})/4)*100; scale=0; b/1" \
              | bc -l)

notify-send -t 750 -a "Brightness" "Brightness:" "${BRIGHTNESS}%"
