#!/usr/bin/env sh

# Add a slight delay to ensure the status has time to update
sleep 0.1

STATUS=$(playerctl status)
if [[ $? == "0" ]]; then
  notify-send -t 3000 -a "Player" "Player: $STATUS" \
    "$(playerctl metadata artist) - $(playerctl metadata title)"
else
  notify-send -t 750 -a "Player" "Player:" "Nothing Playing."
fi

