#!/usr/bin/env sh

# Add a slight delay to ensure the status has time to update
sleep 0.1

STATUS=$(playerctl status)
if [[ $? ]]; then
  notify-send -t 750 -r 5595 \
    "${STATUS}: $(playerctl metadata artist) - $(playerctl metadata title)"
else
  notify-send -t 200 -r 5595 "Nothing Playing."
fi

